ipho_control/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from . import views

app_name = "control"
urlpatterns = [
    path("cockpit", views.cockpit, name="cockpit"),
    path("cockpit/<int:exam_id>", views.cockpit, name="cockpit-id"),
    path(
        "cockpit/<int:exam_id>/changed-phase",
        views.cockpit,
        kwargs={"changed_phase": True},
        name="cockpit-changed-phase",
    ),
    path(
        "cockpit/<int:exam_id>/deleted",
        views.cockpit,
        kwargs={"deleted_phase": True},
        name="cockpit-deleted-phase",
    ),
    path(
        "cockpit/switch-phase/<int:exam_id>/<int:phase_id>",
        views.switch_phase,
        name="switch-phase",
    ),
    path("cockpit/exam_history/<int:exam_id>", views.exam_history, name="exam-history"),
    path("phase/add/<int:exam_id>", views.add_edit_phase, name="add-phase"),
    path("phase/edit/<int:phase_id>", views.add_edit_phase, name="edit-phase"),
    path("phase/delete/<int:phase_id>", views.delete_phase, name="delete-phase"),
    path("phase/summary", views.exam_phase_summary, name="exam-phase-summary"),
]

ipho_download/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path, re_path

from . import views

app_name = "download"
urlpatterns = [
    path("", views.main, {"url": "", "type": "d"}, name="main"),
    re_path(r"add_directory/(?P<url>.*)$", views.add_new_directory, name="add-dir"),
    re_path(r"add_file/(?P<url>.*)$", views.add_new_file, name="add-file"),
    re_path(r"remove/(?P<url>.*)$", views.remove, name="remove"),
    re_path(r"^(?P<type>[fd])/(?P<url>.*)$", views.main, name="path"),
]

ipho_exam/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, path, re_path

from . import views

app_name = "exam"
urlpatterns = [
    path("", views.index, name="index"),
    path("wizard", views.wizard, name="wizard"),
    path("main", views.main, name="main"),
    re_path(r"^translation/list/?$", views.translations_list, name="list"),
    path(
        "translation/add/<int:exam_id>",
        views.add_translation,
        name="add-translation",
    ),
    path(
        "translation/upload/question/<int:question_id>/lang/<int:lang_id>",
        views.add_pdf_node,
        name="upload-translation",
    ),
    path(
        "translation/export/question/<int:question_id>/lang/<int:lang_id>",
        views.translation_export,
        name="export-translation",
    ),
    path(
        "translation/export/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.translation_export,
        name="export-translation-version",
    ),
    path(
        "translation/import/question/<int:question_id>/lang/<int:lang_id>",
        views.translation_import,
        name="import-translation",
    ),
    re_path(
        r"^translation/import/confirm/(?P<slug>[0-9a-z\-]+)$",
        views.translation_import_confirm,
        name="import-translation-confirm",
    ),
    re_path(r"^translation/all/?$", views.list_all_translations, name="list-all"),
    path("auto-translate", views.auto_translate, name="auto-translate"),
    path(
        "auto-translate-count",
        views.auto_translate_count,
        name="auto-translate-count",
    ),
    re_path(r"^languages/?$", views.list_language, name="language-list"),
    path("languages/add", views.add_language, name="language-add"),
    path("languages/edit/<int:lang_id>", views.edit_language, name="language-edit"),
    path("time", views.time_response, name="time"),
    re_path(r"^editor/?$", views.editor),
    path("editor/<int:exam_id>", views.editor, name="editor-exam"),
    path(
        "editor/<int:exam_id>/question/<int:question_id>",
        views.editor,
        name="editor-question",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig/<int:orig_id>",
        views.editor,
        name="editor-orig",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig/<int:orig_id>/lang/<int:lang_id>",
        views.editor,
        name="editor-orig-lang",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig_diff/<int:orig_id>v<int:orig_diff>",
        views.editor,
        name="editor-origdiff",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig_diff/<int:orig_id>v<int:orig_diff>/lang/<int:lang_id>",
        views.editor,
        name="editor-origdiff-lang",
    ),
    path("view", views.exam_view, name="exam-view"),
    path("view/<int:exam_id>", views.exam_view, name="exam-view"),
    path(
        "view/<int:exam_id>/question/<int:question_id>",
        views.exam_view,
        name="exam-view",
    ),
    path(
        "pdf/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        name="pdf",
    ),
    path(
        "pdf/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"solution": True},
        name="pdf-solution",
    ),
    path(
        "pdf/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        name="pdf-version",
    ),
    path(
        "pdf/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"solution": True},
        name="pdf-solution-version",
    ),
    path(
        "pdf-diff/question/<int:question_id>/lang/<int:lang_id>/v<int:old_version_num>/v<int:new_version_num>",
        views.compiled_question_diff,
        name="pdfdiff-version",
    ),
    path(
        "pdf-diff/solution/<int:question_id>/lang/<int:lang_id>/v<int:old_version_num>/v<int:new_version_num>",
        views.compiled_question_diff,
        {"solution": True},
        name="pdfdiff-solution-version",
    ),
    path(
        "tex/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"raw_tex": True},
        name="tex",
    ),
    path(
        "tex/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"raw_tex": True, "solution": True},
        name="tex-solution",
    ),
    path(
        "tex/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"raw_tex": True},
        name="tex-version",
    ),
    path(
        "tex/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"raw_tex": True, "solution": True},
        name="tex-solution-version",
    ),
    path(
        "odt/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_odt,
        name="odt",
    ),
    path(
        "odt/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_odt,
        {"solution": True},
        name="odt-solution",
    ),
    path(
        "odt/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_odt,
        name="odt-version",
    ),
    path(
        "odt/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_odt,
        {"solution": True},
        name="odt-solution-version",
    ),
    path(
        "html/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_html,
        name="html",
    ),
    path(
        "html/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_html,
        {"solution": True},
        name="html-solution",
    ),
    path(
        "html/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_html,
        name="html-version",
    ),
    path(
        "html/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_html,
        {"solution": True},
        name="html-solution-version",
    ),
    path(
        "pdf/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "P"},
        name="pdf-exam-pos-participant",
    ),
    path(
        "pdf/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>/status",
        views.pdf_exam_pos_participant_status,
        name="pdf-exam-pos-participant-status",
    ),
    path(
        "scan/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "S"},
        name="scan-exam-pos-participant",
    ),
    path(
        "scan_orig/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "O"},
        name="scan-orig-exam-pos-participant",
    ),
    re_path(
        r"^print/(?P<doctype>\w)/(?P<exam_id>\d+)/(?P<position>\d+)/participant/(?P<participant_id>\d+)/queue/(?P<queue>.+)$",
        views.print_doc,
        name="print-doc",
    ),
    re_path(r"^pdf-task/(?P<token>[0-9a-z\-]+)$", views.pdf_task, name="pdf-task"),
    re_path(
        r"^pdf-task/(?P<token>[0-9a-z\-]+)/status$",
        views.task_status,
        name="pdf-task-status",
    ),
    re_path(
        r"^pdf-task/(?P<token>[0-9a-z\-]+)/log$", views.task_log, name="pdf-task-log"
    ),
    re_path(r"^feedbacks/list/?$", views.feedbacks_list, name="feedbacks-list"),
    re_path(
        r"^feedbacks/list/(?P<exam_id>\d+)/?$",
        views.feedbacks_list,
        name="feedbacks-list",
    ),
    path("feedbacks/add", views.feedbacks_add_comment, name="feedback-add-comment"),
    path(
        "feedbacks/add/<int:feedback_id>",
        views.feedbacks_add_comment,
        name="feedback-add-comment",
    ),
    path(
        "feedbacks/numbers/<int:exam_id>/<int:question_id>",
        views.feedback_numbers,
        name="feedback-numbers",
    ),
    path(
        "feedbacks/partial/<int:exam_id>/<int:question_id>",
        views.feedback_partial,
        name="feedback-partial",
    ),
    re_path(
        r"^feedbacks/partial/(?P<exam_id>\d+)/(?P<question_id>\d+)/(?P<qml_id>[0-9a-z\-\_]+)$",
        views.feedback_partial,
        name="feedback-partial",
    ),
    re_path(
        r"^feedbacks/(?P<status>(U|L))/(?P<feedback_id>\d+)$",
        views.feedback_partial_like,
        name="feedback-like",
    ),
    re_path(
        r"^feedbacks/thread/?$",
        views.feedback_thread,
        name="feedback-thread",
    ),
    re_path(
        r"^feedbacks/(?P<feedback_id>\d+)/status/(?P<status>\w)$",
        views.feedback_set_status,
        name="feedback-set-status",
    ),
    re_path(
        r"^feedbacks/(?P<feedback_id>\d+)/category/(?P<category>\w)$",
        views.feedback_set_category,
        name="feedback-set-category",
    ),
    path("submission/list", views.submission_exam_list, name="submission-exam-list"),
    path(
        "submission/<int:exam_id>/assign",
        views.submission_exam_assign,
        name="submission-exam-assign",
    ),
    path(
        "submission/<int:exam_id>/confirm",

ipho_poll/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from . import views

app_name = "poll"
urlpatterns = [
    # staff urls
    path("staff/", views.staff_index, name="staff-index"),
    path("staff/room/<int:room_id>", views.staff_index, name="staff-index_room"),
    path(
        "staff/room/<int:room_id>/partials/<slug:qtype>",
        views.staff_index_partial,
        name="staff-index-partials-room",
    ),
    path(
        "staff/room/partials/<slug:qtype>",
        views.staff_index_partial,
        name="staff-index-partials",
    ),
    path(
        "staff/voting/<int:voting_pk>/set/result/<int:result>",
        views.staff_set_result,
        name="staff-set-result",
    ),
    path(
        "staff/voting/<int:voting_pk>/set/impl/<int:impl>",
        views.staff_set_impl,
        name="staff-set-impl",
    ),
    path("voting/detail/<int:voting_pk>/", views.voting_details, name="voting"),
    path(
        "voting/large/<int:voting_pk>/",
        views.voting_large,
        name="voting_large",
    ),
    path("voting/add/room/<int:room_id>", views.add_voting, name="add-voting-in-room"),
    path("voting/add/main", views.add_voting, name="add-voting"),
    path(
        "voting/<int:voting_pk>/delete/",
        views.delete_voting,
        name="delete-voting",
    ),
    path(
        "voting/<int:voting_pk>/edit/",
        views.edit_voting,
        name="edit-voting",
    ),
    path("voting/<int:voting_pk>/", views.set_end_date, name="set-end-date"),
    path(
        "voting/<int:voting_pk>/add_minutes/<int:minutes>/",
        views.add_minutes,
        name="add-minutes",
    ),
    path(
        "voting/<int:voting_pk>/close",
        views.close_voting,
        name="close-voting",
    ),
    path(
        "voting/<int:voting_pk>/reopen",
        views.reopen_voting,
        name="reopen-voting",
    ),
    path("room/edit/<int:room_id>", views.edit_room, name="edit-room"),
    # delegation urls
    path("", views.voter_index, name="voter-index"),
    path("room/<int:room_id>", views.voter_index, name="voter-index_room"),
    path("err/<int:err_id>", views.voter_index, name="voter-index_err"),
    path(
        "room/<int:room_id>/err/<int:err_id>",
        views.voter_index,
        name="voter-index_room_err",
    ),
    path("voted/room/<int:room_id>", views.voted, name="voted_room"),
    path("voted/", views.voted, name="voted"),
]

ipho_print/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from . import views

app_name = "print"
urlpatterns = [
    path("", views.main, name="main"),
]

templates/pages/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <style>
    .with-logo {
    	background: #eee url('{% static "logo_square.png" %}') center right no-repeat;
    	-webkit-background-clip: padding-box;
    	background-clip: padding-box;
    	background-origin: content-box;
    	-webkit-background-origin: content-box;
        background-size: 205px 200px;
/*    	width: 100%;
    	height: 100%;*/
    }

    .panel-heading .accordion-toggle:after {
    font-family: 'Glyphicons Halflings';  
    content: "\e114"; 
    float: right; 
    color:rgb(0, 0, 0); 
    }
    .panel-heading.collapsed .accordion-toggle:after {
        content: "\e080";
    }
    </style>

<div class="container">
  <div class="jumbotron with-logo hidden-sm hidden-xs">
      <h1>Exam Tools</h1>
      <p>
          Supporting the academic work of Science Olympiads.
      </p>
  </div>
  <div class="jumbotron hidden-lg hidden-md">
      <h1>Exam Tools</h1>
      <p>
          Supporting the academic work of Science Olympiads.
      </p>
  </div>
</div> <!-- /container -->

<div class="container">
    <div class="row">
        <div class="col-md-9">
          <h2>Welcome</h2>
          <p>
              Originally developed for the International Physics Olympiad 2016 held in Zurich, Switzerland, Exam Tools has since
              been used at several Scientific Olympiads to support the exam discussion, translation and administration process.
              Exam feedbacks, translations, printing, voting, corrections and ranking are among the features of this new tool.
              {% if OFFICIALLY_SUPPORTED %}
              The <a href="http://oly-exams.org">OlyExams</a> team and the local organizers are proud to offer Exam Tools also for the present Olympiad.
              {% endif %}
          </p>
          <p>
              During the registration process you will need to confirm that your delegation will join with at least one supported notebook computer, and that you were successfully able to translate the test exams. Note that the organizers will not provide any notebooks or workstations to the delegations (except upon prior arrangement).
          </p>
          <p>
            Please see <a href="http://oly-exams.org">www.oly-exams.org</a> if you consider using
            ExamTools for your own Olympiad, and also try our publicly available <a href="http://demo.oly-exams.org">demo</a>.
          </p>

          {% if DEMO_MODE %}
          <p>Within this demo version you can perfom the translation and submission of previous years' exams.</p>
          {% endif %}
          {% if perms.ipho_core.can_see_boardmeeting %}
          <h3>Step-by-step guide</h3>
          <p>To guide you through the translation process, we prepared a step-by-step guide which explains the basic steps needed for testing your notebook.</p>
          {% if DEMO_MODE %}
          <p class="text-center"><a class="btn btn-primary btn-lg" href="{% url 'exam:wizard' %}">Try it now!</a></p>
          {% else %}
          <p class="text-center"><a class="btn btn-primary btn-lg" href="{% url 'exam:wizard' %}">Get started!</a></p>
          {% endif %}
          {% if control_show_phases %}
          <hr />
            <div id="exam-summary-header" style="display:flex; justify-content: space-between; align-items: center;">
                <div style="width: 85%;">
                    <h2>Exam Phases</h2>
                    <p>Below you can see the phases the different Exams are in.</p>
                </div>
                <div id="exam-summary-reload-container">
                    <button class="btn btn-default btn-lg" id="exam-summary-reload" style="font-size:22px;">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                    </button>
                </div>
                
            </div>
            <div id="exam-summary-container" data-href="{% url 'control:exam-phase-summary' %}"></div>
          {% endif %}
          <hr />
          <p><strong>Navigation:</strong> Below you find a summary of the Exam Tools structure. The same navigation is available in the upper bar on all pages.</p>

          <div class="row">
              <div class="col-sm-4">
                  <h3>Exam</h3>
                  <ul>
                    {% if perms.ipho_core.is_delegation and not user.is_superuser %}
                      <li>
                          <h4>Step-by-step guide</h4>
                          <ul>
                              <li>
                                <a href="{% url 'exam:wizard' %}">Get started!</a>
                              </li>
                          </ul>
                      </li>

                      <li>
                          <h4>Translations</h4>
                          <ul>
                              <li>
                                  <a href="{% url 'exam:language-list' %}">
                                      Define languages
                                  </a>
                              </li>
                              <li>
                                  <a href="{% url 'exam:list' %}">
                                      My translations
                                  </a>
                              </li>
                              <li>
                                  <a href="{% url 'exam:submission-exam-list' %}">
                                      Final submission
                                  </a>
                              </li>
                          </ul>
                      </li>
                      {% endif %}
                      <li>
                          <h4>All translations</h4>
                          <ul>
                              <li>
                                  <a href="{% url 'exam:exam-view' %}">
                                      View official English exam
                                  </a>
                              </li>
                              <li>
                                  <a href="{% url 'exam:list-all' %}">
                                      View all translations
                                  </a>
                              </li>
                          </ul>
                      </li>

                      <li>
                          <h4>Exam feedbacks</h4>
                          <ul>
                              <li>
                                  <a href="{% url 'exam:feedbacks-list' %}">
                                      {% if perms.ipho_core.is_delegation and not user.is_superuser %}View{% else %}Manage{% endif %} feedbacks
                                  </a>
                              </li>
                          </ul>
                      </li>

                  </ul>

              </div>

              <div class="col-sm-4">
                {% if perms.ipho_core.is_delegation and not user.is_superuser %}
                <h3>Results</h3>
                <ul>
                    <li>
                        <a href="{% url 'marking:delegation-summary' %}">
                            View and submit marks
                        </a>
                    </li>
                </ul>
                {% endif %}
                {% if perms.ipho_core.can_vote and not user.is_superuser %}
                  <h3>Voting</h3>
                  <ul>
                      <li>
                          <a href="{% url 'poll:voter-index' %}">
                              Vote
                          </a>
                      </li>
                  </ul>
                {% endif %}
              </div>

              <div class="col-sm-4">
                <h3>Downloads</h3>
                <ul>
                    <li>
                        <a href="{% url 'download:main' %}">
                            View and download resources
                        </a>
                    </li>
                </ul>
                {% if perms.ipho_core.can_print_boardmeeting_site or perms.ipho_core.can_print_exam_site %}
                <h3>Print</h3>
                <ul>
                    <li>
                        <a href="{% url 'print:main' %}">
                            Print documents
                        </a>
                    </li>
                </ul>
                {% endif %}
              </div>

          </div>
          {% endif %}


        </div>
        <div class="col-md-3">
          <h2>Help</h2>
          <p>Please contact a guide or IT staff member if you need help with ExamTools or you notice something malfunctioning.
              {% if OFFICIALLY_SUPPORTED %}
              {{ SUPPORT_CONTACT | safe }}
              {% else %}
              Note that this event is run without OlyExams support.
              {% endif %}
            </p>

          <h2>User guide</h2>
          <p>Please refer to the documentation section for a detailed user guide which explains the Exam Tools and how to perfom a test exam translation required by the registration process.</p>
          <p><a class="btn btn-default" href="{{ DOCS_URL }}">View the docs <i class="fa fa-angle-double-right"></i></a></p>

        </div>
    </div>

</div> <!-- /container -->


{% endblock %}

{% block extra-script %}
<script>
// Utils functions:

let isSubscribed = false;
let swRegistration = null;

function urlB64ToUint8Array (base64String) {
    var padding = '='.repeat((4 - base64String.length % 4) % 4)
    var base64 = (base64String + padding)
        .replace(/\-/g, '+')
        .replace(/_/g, '/')
    var rawData = window.atob(base64)
    var outputArray = new Uint8Array(rawData.length)
    for (var i = 0; i < rawData.length; ++i) {
        outputArray[i] = rawData.charCodeAt(i)
    }
    return outputArray;
};
/*    function initializeUI() {
// Set the initial subscription value
swRegistration.pushManager.getSubscription()
.then(function(subscription) {
  isSubscribed = !(subscription === null);

  if (isSubscribed) {
    console.log('User IS subscribed.');
  } else {
    console.log('User is NOT subscribed.');
  }

  //updateBtn();
});
}*/

function checkStatus() {
  return new Promise((resolve, reject) => {
    if ('serviceWorker' in navigator && 'PushManager' in window) {
      console.log('Service Worker and Push is supported');
      navigator.serviceWorker.register("{% url 'service_worker' %}")
      .then(function(swReg) {
        console.log('Service Worker is registered', swReg);
        swRegistration = swReg;
        resolve('SUCCESS');
        //initializeUI();
      })
      .catch(function(error) {
        console.error('Service Worker Error', error);
        resolve(error);
      });
    } else {
      console.warn('Push messaging is not supported');
      reject("NOT SUPPORTED");
      //pushButton.textContent = 'Push Not Supported';
    }
  })
}

var applicationServerPublicKey = "{{ push_key }}";
// In your ready listener
function subscribeUser() {
  const applicationServerKey = urlB64ToUint8Array(applicationServerPublicKey);
  console.log('subscribing...');
  swRegistration.pushManager.subscribe({
    userVisibleOnly: true,
    applicationServerKey: applicationServerKey
  })
  .then(function(subscription) {
    console.log('User is subscribed.');
    data = {};
    data.subs = subscription.toJSON();
    console.log(data);
    data.csrfmiddlewaretoken = '{{ csrf_token }}';
    $.ajax({
        url: "{% url 'push_submission' %}",
        type: 'POST',
        data: data,
        success: function(data) {
            if (!data['success']) {
                console.log('subscription could not be saved');
                console.log(data);
            }
      }
    });
    isSubscribed = true;
    //updateBtn();
  })
  .catch(function(err) {
    console.log('Failed to subscribe the user: ', err);
    //updateBtn();
  });
}

{% if control_show_phases %}
function load_exam_phase_summary() {
    $.ajax({
        url: $("#exam-summary-container").data("href"),
        dataType: 'json',
        success: function(data) {
            if(data['success']){
                $("#exam-summary-container").html(data['body']);
                $("time[data-format]").each(function () {
                  var el = $(this);
                  var dt = moment(el.attr("datetime"));
                  el.text(dt.format(el.data("format")));
                });
                setTimeout(function(){
                    $('#exam-summary-reload').removeClass("disabled");
                    $('#exam-summary-reload-container').prop("title", "");
                    $('#exam-summary-reload-container').tooltip("destroy");
                },5000)
            }
        }
    });
}
{% endif %}

$(document).ready(function() {
  checkStatus().then(function () {
    {% if push %}
    subscribeUser();
    {% endif %}
  });

  {% if control_show_phases %}
  load_exam_phase_summary();
  
  $('#exam-summary-reload').on("click",function(e){
      e.preventDefault();
      $('#exam-summary-reload').addClass("disabled");
      $('#exam-summary-reload-container').prop("title", "Please wait 5 seconds before reloading again.");
      $('#exam-summary-reload-container').tooltip();
      load_exam_phase_summary();
  });
  {% endif %}

});

</script>
{% endblock %}