ipho_download/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path, re_path

from . import views

app_name = "download"
urlpatterns = [
    path("", views.main, {"url": "", "type": "d"}, name="main"),
    re_path(r"add_directory/(?P<url>.*)$", views.add_new_directory, name="add-dir"),
    re_path(r"add_file/(?P<url>.*)$", views.add_new_file, name="add-file"),
    re_path(r"remove/(?P<url>.*)$", views.remove, name="remove"),
    re_path(r"^(?P<type>[fd])/(?P<url>.*)$", views.main, name="path"),
]

ipho_exam/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, path, re_path

from . import views

app_name = "exam"
urlpatterns = [
    path("", views.index, name="index"),
    path("wizard", views.wizard, name="wizard"),
    path("main", views.main, name="main"),
    re_path(r"^translation/list/?$", views.translations_list, name="list"),
    path(
        "translation/add/<int:exam_id>",
        views.add_translation,
        name="add-translation",
    ),
    path(
        "translation/upload/question/<int:question_id>/lang/<int:lang_id>",
        views.add_pdf_node,
        name="upload-translation",
    ),
    path(
        "translation/export/question/<int:question_id>/lang/<int:lang_id>",
        views.translation_export,
        name="export-translation",
    ),
    path(
        "translation/export/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.translation_export,
        name="export-translation-version",
    ),
    path(
        "translation/import/question/<int:question_id>/lang/<int:lang_id>",
        views.translation_import,
        name="import-translation",
    ),
    re_path(
        r"^translation/import/confirm/(?P<slug>[0-9a-z\-]+)$",
        views.translation_import_confirm,
        name="import-translation-confirm",
    ),
    re_path(r"^translation/all/?$", views.list_all_translations, name="list-all"),
    path("auto-translate", views.auto_translate, name="auto-translate"),
    path(
        "auto-translate-count",
        views.auto_translate_count,
        name="auto-translate-count",
    ),
    re_path(r"^languages/?$", views.list_language, name="language-list"),
    path("languages/add", views.add_language, name="language-add"),
    path("languages/edit/<int:lang_id>", views.edit_language, name="language-edit"),
    path("time", views.time_response, name="time"),
    re_path(r"^editor/?$", views.editor),
    path("editor/<int:exam_id>", views.editor, name="editor-exam"),
    path(
        "editor/<int:exam_id>/question/<int:question_id>",
        views.editor,
        name="editor-question",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig/<int:orig_id>",
        views.editor,
        name="editor-orig",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig/<int:orig_id>/lang/<int:lang_id>",
        views.editor,
        name="editor-orig-lang",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig_diff/<int:orig_id>v<int:orig_diff>",
        views.editor,
        name="editor-origdiff",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig_diff/<int:orig_id>v<int:orig_diff>/lang/<int:lang_id>",
        views.editor,
        name="editor-origdiff-lang",
    ),
    path("view", views.exam_view, name="exam-view"),
    path("view/<int:exam_id>", views.exam_view, name="exam-view"),
    path(
        "view/<int:exam_id>/question/<int:question_id>",
        views.exam_view,
        name="exam-view",
    ),
    path(
        "pdf/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        name="pdf",
    ),
    path(
        "pdf/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"solution": True},
        name="pdf-solution",
    ),
    path(
        "pdf/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        name="pdf-version",
    ),
    path(
        "pdf/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"solution": True},
        name="pdf-solution-version",
    ),
    path(
        "pdf-diff/question/<int:question_id>/lang/<int:lang_id>/v<int:old_version_num>/v<int:new_version_num>",
        views.compiled_question_diff,
        name="pdfdiff-version",
    ),
    path(
        "pdf-diff/solution/<int:question_id>/lang/<int:lang_id>/v<int:old_version_num>/v<int:new_version_num>",
        views.compiled_question_diff,
        {"solution": True},
        name="pdfdiff-solution-version",
    ),
    path(
        "tex/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"raw_tex": True},
        name="tex",
    ),
    path(
        "tex/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"raw_tex": True, "solution": True},
        name="tex-solution",
    ),
    path(
        "tex/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"raw_tex": True},
        name="tex-version",
    ),
    path(
        "tex/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"raw_tex": True, "solution": True},
        name="tex-solution-version",
    ),
    path(
        "odt/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_odt,
        name="odt",
    ),
    path(
        "odt/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_odt,
        {"solution": True},
        name="odt-solution",
    ),
    path(
        "odt/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_odt,
        name="odt-version",
    ),
    path(
        "odt/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_odt,
        {"solution": True},
        name="odt-solution-version",
    ),
    path(
        "html/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_html,
        name="html",
    ),
    path(
        "html/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_html,
        {"solution": True},
        name="html-solution",
    ),
    path(
        "html/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_html,
        name="html-version",
    ),
    path(
        "html/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_html,
        {"solution": True},
        name="html-solution-version",
    ),
    path(
        "pdf/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "P"},
        name="pdf-exam-pos-participant",
    ),
    path(
        "pdf/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>/status",
        views.pdf_exam_pos_participant_status,
        name="pdf-exam-pos-participant-status",
    ),
    path(
        "scan/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "S"},
        name="scan-exam-pos-participant",
    ),
    path(
        "scan_orig/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "O"},
        name="scan-orig-exam-pos-participant",
    ),
    re_path(
        r"^print/(?P<doctype>\w)/(?P<exam_id>\d+)/(?P<position>\d+)/participant/(?P<participant_id>\d+)/queue/(?P<queue>.+)$",
        views.print_doc,
        name="print-doc",
    ),
    re_path(r"^pdf-task/(?P<token>[0-9a-z\-]+)$", views.pdf_task, name="pdf-task"),
    re_path(
        r"^pdf-task/(?P<token>[0-9a-z\-]+)/status$",
        views.task_status,
        name="pdf-task-status",
    ),
    re_path(
        r"^pdf-task/(?P<token>[0-9a-z\-]+)/log$", views.task_log, name="pdf-task-log"
    ),
    re_path(r"^feedbacks/list/?$", views.feedbacks_list, name="feedbacks-list"),
    re_path(
        r"^feedbacks/list/(?P<exam_id>\d+)/?$",
        views.feedbacks_list,
        name="feedbacks-list",
    ),
    path("feedbacks/add", views.feedbacks_add_comment, name="feedback-add-comment"),
    path(
        "feedbacks/add/<int:feedback_id>",
        views.feedbacks_add_comment,
        name="feedback-add-comment",
    ),
    path(
        "feedbacks/numbers/<int:exam_id>/<int:question_id>",
        views.feedback_numbers,
        name="feedback-numbers",
    ),
    path(
        "feedbacks/partial/<int:exam_id>/<int:question_id>",
        views.feedback_partial,
        name="feedback-partial",
    ),
    re_path(
        r"^feedbacks/partial/(?P<exam_id>\d+)/(?P<question_id>\d+)/(?P<qml_id>[0-9a-z\-\_]+)$",
        views.feedback_partial,
        name="feedback-partial",
    ),
    re_path(
        r"^feedbacks/(?P<status>(U|L))/(?P<feedback_id>\d+)$",
        views.feedback_partial_like,
        name="feedback-like",
    ),
    re_path(
        r"^feedbacks/thread/?$",
        views.feedback_thread,
        name="feedback-thread",
    ),
    re_path(
        r"^feedbacks/(?P<feedback_id>\d+)/status/(?P<status>\w)$",
        views.feedback_set_status,
        name="feedback-set-status",
    ),
    re_path(
        r"^feedbacks/(?P<feedback_id>\d+)/category/(?P<category>\w)$",
        views.feedback_set_category,
        name="feedback-set-category",
    ),
    path("submission/list", views.submission_exam_list, name="submission-exam-list"),
    path(
        "submission/<int:exam_id>/assign",
        views.submission_exam_assign,
        name="submission-exam-assign",
    ),
    path(
        "submission/<int:exam_id>/confirm",

ipho_download/models.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# from django.db import models

# Create your models here.

ipho_download/forms.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms


class NewFileForm(forms.Form):
    file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field("file"),
        )
        self.helper.html5_required = True
        self.helper.form_show_labels = True
        self.helper.disable_csrf = True


class NewDirectoryForm(forms.Form):
    directory = forms.SlugField(max_length=100)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field("directory"),
        )
        self.helper.html5_required = True
        self.helper.form_show_labels = True

templates/ipho_download/main.html
{% extends "base.html" %}

{% load humanize %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="page-header">
      <h1>Downloads</h1>
    </div>

    <ol class="breadcrumb">
      {% for p,l in cur_path %}
      <li><a href="{% url 'download:path' type='d' url=l %}">{{ p|default:'/' }}</a></li>
      {% endfor %}
    </ol>

    
    {% with last=cur_path|last %}
    <h3>Content of {{ last.0 }}{% if last.0 != '/' %}/{% endif %}</h3>
    {% endwith %}
    {% if perms.ipho_core.is_organizer_admin %}  
      <button id="upload-file-button" type="button" class="btn btn-default btn-s" data-toggle="modal" data-target="#new-file-modal">
        <i class="fa fa-upload fa-fw"></i> Upload file
      </button>
      <button id="add-folder-button" type="button" class="btn btn-default btn-s" data-toggle="modal" data-target="#new-directory-modal">
        <i class="fa fa-folder fa-fw"></i> Add folder
      </button>
      <br>
     <br>
    {% endif %}
    <table class="table table-striped">
      {% for t,tshort,name,link,fsize,mtime in flist %}
      <tr>
        <td>
          <i class="fa fa-{{ t }}"></i>
          <a class="download-item" href="{% url 'download:path' type=tshort url=link %}">
          {{ name }}
          </a>
          {% if tshort == 'f' %}
          &nbsp;&nbsp;{{ fsize|filesizeformat }}, last changed {{ mtime|naturaltime }} ({{ mtime|date:'Y-m-d H:iO' }})
          {% endif %}
        </td>
        <td>
          {% if perms.ipho_core.is_organizer_admin and tshort == "f" or user.is_superuser %}
          <button type="button" class="btn btn-danger btn-xs remove-button" data-toggle="modal" data-target="#remove-modal" data-href="{% url 'download:remove' url=link %}" data-name="{{ name }}">
            <i class="fa fa-trash-o fa-fw"></i>
          </button>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>

</div> <!-- /container -->

<div class="modal fade" id="new-file-modal" tabindex="-1">
  <div class="modal-dialog">
      <form method="post" action="{% url 'download:add-file' url=url %}">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
        <h4 class="modal-title">Upload file</h4>
      </div>

          <div class="modal-body">
            {{ file_form }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button id="new-file-modal-submit" type="submit" class="btn btn-primary">Upload</button>
          </div>
      </div>
      </form>
  </div>
</div>

<div class="modal fade" id="new-directory-modal" tabindex="-1">
  <div class="modal-dialog">
      <form method="post" action="{% url 'download:add-dir' url=url %}">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
        <h4 class="modal-title">Add folder</h4>
      </div>

          <div class="modal-body">
            {{ dir_form }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button id="new-directory-modal-submit" type="submit" class="btn btn-primary">Add</button>
          </div>
      </div>
      </form>
  </div>
</div>

<div class="modal fade" id="remove-modal" tabindex="-1">
  <div class="modal-dialog">
      <form method="post" action="">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
        <h4 class="modal-title">Remove</h4>
      </div>

          <div class="modal-body">
            Do you really want to remove this file?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Remove</button>
          </div>
      </div>
      </form>
  </div>
</div>

{% endblock %}



{% block extra-script %}
<script>
$(function() {
    // Get csrftoken
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $(document).on('submit', '#new-directory-modal form', function(evt) {
        var form = evt.target;
        var $form = $(form);
        evt.preventDefault();
        var data = new FormData($form.get(0));
        $.ajax({
            url: form.action,
            type: form.method,
            data: data,
            cache: false,
            processData: false,
            contentType: false,
            success: function(data) {
                if (!data['success']) {
                  if (data['form']){
                    $('#new-directory-modal .modal-body').html(data['form']).find("[data-toggle=popover]").popover();
                    return;
                  }
                  if (data['error']){
                    $('#new-directory-modal .modal-body').html(data["error"]);
                  }
                }else{
                  location.reload(); 
                }
            }
        });
    });

    $(document).on('submit', '#new-file-modal form', function(evt) {
        var form = evt.target;
        var $form = $(form);
        evt.preventDefault();
        var data = new FormData($form.get(0));
        $.ajax({
            url: form.action,
            type: form.method,
            data: data,
            cache: false,
            processData: false,
            contentType: false,
            success: function(data) {
                if (!data['success']) {
                  if (data['form']){
                    $('#new-file-modal .modal-body').html(data['form']).find("[data-toggle=popover]").popover();
                    return;
                  }
                  if (data['error']){
                    $('#new-file-modal .modal-body').html(data["error"]);
                  }
                }else{
                  location.reload(); 
                }
            }
        });
    });

    $(document).on('submit', '#remove-modal form', function(evt) {
        var form = evt.target;
        var $form = $(form);
        evt.preventDefault();
        var data = new FormData($form.get(0));
        $.ajax({
            url: form.action,
            type: form.method,
            cache: false,
            processData: false,
            contentType: false,
            success: function(data) {
                if (!data['success']) {
                  if (data['error']){
                    $('#remove-modal .modal-body').html(data["error"]);
                  }
                }else{
                  location.reload(); 
                }
            }
        });
    });

    $('#remove-modal').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget); // Button that triggered the modal
        var action = button.data('href');
        $(this).find("form").attr('action', action);
        var name = button.data('name');
        $(this).find(".modal-body").html("Do you wan to remove " + name + " ?");
    });

    

});
</script>
{% endblock %}