ipho_exam/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import include, path, re_path

from . import views

app_name = "exam"
urlpatterns = [
    path("", views.index, name="index"),
    path("wizard", views.wizard, name="wizard"),
    path("main", views.main, name="main"),
    re_path(r"^translation/list/?$", views.translations_list, name="list"),
    path(
        "translation/add/<int:exam_id>",
        views.add_translation,
        name="add-translation",
    ),
    path(
        "translation/upload/question/<int:question_id>/lang/<int:lang_id>",
        views.add_pdf_node,
        name="upload-translation",
    ),
    path(
        "translation/export/question/<int:question_id>/lang/<int:lang_id>",
        views.translation_export,
        name="export-translation",
    ),
    path(
        "translation/export/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.translation_export,
        name="export-translation-version",
    ),
    path(
        "translation/import/question/<int:question_id>/lang/<int:lang_id>",
        views.translation_import,
        name="import-translation",
    ),
    re_path(
        r"^translation/import/confirm/(?P<slug>[0-9a-z\-]+)$",
        views.translation_import_confirm,
        name="import-translation-confirm",
    ),
    re_path(r"^translation/all/?$", views.list_all_translations, name="list-all"),
    path("auto-translate", views.auto_translate, name="auto-translate"),
    path(
        "auto-translate-count",
        views.auto_translate_count,
        name="auto-translate-count",
    ),
    re_path(r"^languages/?$", views.list_language, name="language-list"),
    path("languages/add", views.add_language, name="language-add"),
    path("languages/edit/<int:lang_id>", views.edit_language, name="language-edit"),
    path("time", views.time_response, name="time"),
    re_path(r"^editor/?$", views.editor),
    path("editor/<int:exam_id>", views.editor, name="editor-exam"),
    path(
        "editor/<int:exam_id>/question/<int:question_id>",
        views.editor,
        name="editor-question",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig/<int:orig_id>",
        views.editor,
        name="editor-orig",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig/<int:orig_id>/lang/<int:lang_id>",
        views.editor,
        name="editor-orig-lang",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig_diff/<int:orig_id>v<int:orig_diff>",
        views.editor,
        name="editor-origdiff",
    ),
    path(
        "editor/<int:exam_id>/question/<int:question_id>/orig_diff/<int:orig_id>v<int:orig_diff>/lang/<int:lang_id>",
        views.editor,
        name="editor-origdiff-lang",
    ),
    path("view", views.exam_view, name="exam-view"),
    path("view/<int:exam_id>", views.exam_view, name="exam-view"),
    path(
        "view/<int:exam_id>/question/<int:question_id>",
        views.exam_view,
        name="exam-view",
    ),
    path(
        "pdf/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        name="pdf",
    ),
    path(
        "pdf/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"solution": True},
        name="pdf-solution",
    ),
    path(
        "pdf/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        name="pdf-version",
    ),
    path(
        "pdf/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"solution": True},
        name="pdf-solution-version",
    ),
    path(
        "pdf-diff/question/<int:question_id>/lang/<int:lang_id>/v<int:old_version_num>/v<int:new_version_num>",
        views.compiled_question_diff,
        name="pdfdiff-version",
    ),
    path(
        "pdf-diff/solution/<int:question_id>/lang/<int:lang_id>/v<int:old_version_num>/v<int:new_version_num>",
        views.compiled_question_diff,
        {"solution": True},
        name="pdfdiff-solution-version",
    ),
    path(
        "tex/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"raw_tex": True},
        name="tex",
    ),
    path(
        "tex/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question,
        {"raw_tex": True, "solution": True},
        name="tex-solution",
    ),
    path(
        "tex/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"raw_tex": True},
        name="tex-version",
    ),
    path(
        "tex/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question,
        {"raw_tex": True, "solution": True},
        name="tex-solution-version",
    ),
    path(
        "odt/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_odt,
        name="odt",
    ),
    path(
        "odt/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_odt,
        {"solution": True},
        name="odt-solution",
    ),
    path(
        "odt/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_odt,
        name="odt-version",
    ),
    path(
        "odt/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_odt,
        {"solution": True},
        name="odt-solution-version",
    ),
    path(
        "html/question/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_html,
        name="html",
    ),
    path(
        "html/solution/<int:question_id>/lang/<int:lang_id>",
        views.compiled_question_html,
        {"solution": True},
        name="html-solution",
    ),
    path(
        "html/question/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_html,
        name="html-version",
    ),
    path(
        "html/solution/<int:question_id>/lang/<int:lang_id>/v<int:version_num>",
        views.compiled_question_html,
        {"solution": True},
        name="html-solution-version",
    ),
    path(
        "pdf/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "P"},
        name="pdf-exam-pos-participant",
    ),
    path(
        "pdf/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>/status",
        views.pdf_exam_pos_participant_status,
        name="pdf-exam-pos-participant-status",
    ),
    path(
        "scan/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "S"},
        name="scan-exam-pos-participant",
    ),
    path(
        "scan_orig/exam/<int:exam_id>/<int:position>/participant/<int:participant_id>",
        views.pdf_exam_pos_participant,
        {"type": "O"},
        name="scan-orig-exam-pos-participant",
    ),
    re_path(
        r"^print/(?P<doctype>\w)/(?P<exam_id>\d+)/(?P<position>\d+)/participant/(?P<participant_id>\d+)/queue/(?P<queue>.+)$",
        views.print_doc,
        name="print-doc",
    ),
    re_path(r"^pdf-task/(?P<token>[0-9a-z\-]+)$", views.pdf_task, name="pdf-task"),
    re_path(
        r"^pdf-task/(?P<token>[0-9a-z\-]+)/status$",
        views.task_status,
        name="pdf-task-status",
    ),
    re_path(
        r"^pdf-task/(?P<token>[0-9a-z\-]+)/log$", views.task_log, name="pdf-task-log"
    ),
    re_path(r"^feedbacks/list/?$", views.feedbacks_list, name="feedbacks-list"),
    re_path(
        r"^feedbacks/list/(?P<exam_id>\d+)/?$",
        views.feedbacks_list,
        name="feedbacks-list",
    ),
    path("feedbacks/add", views.feedbacks_add_comment, name="feedback-add-comment"),
    path(
        "feedbacks/add/<int:feedback_id>",
        views.feedbacks_add_comment,
        name="feedback-add-comment",
    ),
    path(
        "feedbacks/numbers/<int:exam_id>/<int:question_id>",
        views.feedback_numbers,
        name="feedback-numbers",
    ),
    path(
        "feedbacks/partial/<int:exam_id>/<int:question_id>",
        views.feedback_partial,
        name="feedback-partial",
    ),
    re_path(
        r"^feedbacks/partial/(?P<exam_id>\d+)/(?P<question_id>\d+)/(?P<qml_id>[0-9a-z\-\_]+)$",
        views.feedback_partial,
        name="feedback-partial",
    ),
    re_path(
        r"^feedbacks/(?P<status>(U|L))/(?P<feedback_id>\d+)$",
        views.feedback_partial_like,
        name="feedback-like",
    ),
    re_path(
        r"^feedbacks/thread/?$",
        views.feedback_thread,
        name="feedback-thread",
    ),
    re_path(
        r"^feedbacks/(?P<feedback_id>\d+)/status/(?P<status>\w)$",
        views.feedback_set_status,
        name="feedback-set-status",
    ),
    re_path(
        r"^feedbacks/(?P<feedback_id>\d+)/category/(?P<category>\w)$",
        views.feedback_set_category,
        name="feedback-set-category",
    ),
    path("submission/list", views.submission_exam_list, name="submission-exam-list"),
    path(
        "submission/<int:exam_id>/assign",
        views.submission_exam_assign,
        name="submission-exam-assign",
    ),
    path(
        "submission/<int:exam_id>/confirm",

ipho_marking/urls.py
# Exam Tools
#
# Copyright (C) 2014 - 2023 Oly Exams Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path, re_path

from . import views

app_name = "marking"
urlpatterns = [
    ## Delegation views
    path("", views.delegation_summary, name="delegation-summary"),
    path(
        "export/all",
        views.delegation_export,
        name="delegation-export-all",
    ),
    path(
        "export/exam/<int:exam_id>",
        views.delegation_export,
        name="delegation-export",
    ),
    path(
        "detail/<int:ppnt_id>/question/<int:question_id>",
        views.delegation_ppnt_view,
        name="delegation-ppnt-detail",
    ),
    path(
        "detail_all/question/<int:question_id>",
        views.delegation_view_all,
        name="delegation-all-detail",
    ),
    path(
        "detail/<int:ppnt_id>/question/<int:question_id>/edit",
        views.delegation_ppnt_edit,
        name="delegation-ppnt-detail-edit",
    ),
    path(
        "detail_all/question/<int:question_id>/edit",
        views.delegation_edit_all,
        name="delegation-all-detail-edit",
    ),
    path(
        "confirm/<int:question_id>",
        views.delegation_confirm,
        name="delegation-confirm",
    ),
    path(
        "confirm/final/<int:question_id>",
        views.delegation_confirm,
        name="delegation-final-confirm",
        kwargs={"final_confirmation": True},
    ),
    ## Markers
    re_path(
        r"^official/?$", views.official_marking_index, name="official-marking-index"
    ),
    path(
        "official/question/<int:question_id>",
        views.official_marking_index,
        name="official-marking-index-question",
    ),
    path(
        "official/question/<int:question_id>/template",
        views.create_marking_template,
        name="official-marking-template",
    ),
    path(
        "official/question/<int:question_id>/delegation/<int:delegation_id>",
        views.official_marking_detail,
        name="official-marking-detail",
    ),
    path(
        "official/question/<int:question_id>/delegation/<int:delegation_id>/confirmed",
        views.official_marking_confirmed,
        name="official-marking-confirmed",
    ),
    ## Moderations views
    re_path(r"^moderate/?$", views.moderation_index, name="moderation-index"),
    path(
        "moderate/question/<int:question_id>",
        views.moderation_index,
        name="moderation-index-question",
    ),
    path(
        "moderate/question/<int:question_id>/delegation/<int:delegation_id>",
        views.moderation_detail,
        name="moderation-detail",
    ),
    path(
        "moderate/question/<int:question_id>/delegation/<int:delegation_id>/confirmed",
        views.moderation_confirmed,
        name="moderation-confirmed",
    ),
    ##  staff views
    re_path(r"^staff/import/?$", views.import_exam, name="import-exam"),
    re_path(r"^staff/?$", views.summary, name="summary"),
    re_path(
        r"^staff/v(?P<version>\w)/participant/(?P<ppnt_id>\d+)/question/(?P<question_id>\d+)/edit$",
        views.staff_ppnt_detail,
        name="staff-ppnt-detail",
    ),
    path(
        "export-countries-to-moderate.csv",
        views.export_countries_to_moderate,
        name="countries-to-moderate",
    ),
    path("all/export.csv", views.export, name="export"),
    path(
        "all/export-final.csv",
        views.export_sql,
        name="export-total",
        kwargs={"versions": ["F"]},
    ),
    path("marking-submissions", views.marking_submissions, name="marking-submissions"),
    path("progress", views.progress, name="progress"),
    path("ranking", views.ranking, name="ranking"),
    path("export-ranking-csv", views.export_ranking_csv, name="export-ranking-csv"),
]

templates/ipho_exam/admin_feedbacks_export.html
{% extends "ipho_exam/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra-head %}
{% endblock %}

{% block breadcrumb %}
<li><a href="#">Admin</a></li>
<li class="active">Export feedbacks</li>
{% endblock %}

{% block pageheader %}<h1>Export feedbacks</h1>{% endblock %}

{% block exam-content %}
<p class="lead">Select the question from which you want to export the feedbacks.</p>

<div class="row">
  {% regroup questions by exam as questions_list %}
  {% for exam_questions in questions_list %}
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>{{ exam_questions.grouper.name }}</h4>
      </div>
      <div class="list-group">
        {% for q in exam_questions.list %}
        <a class="list-group-item" href="{% url 'exam:admin-feedbacks-export-csv' exam_id=q.exam.pk question_id=q.pk %}">
          {{ q.name }}
          <span class="pull-right">
            <i class="fa fa-file-excel-o"></i>
            <i class="fa fa-chevron-right"></i>
          </span>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

{% block extra-script %}
{% endblock %}

templates/ipho_exam/admin_scan_progress.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra-head %}
{% if question %}
<meta http-equiv="refresh" content="30" />
{% endif %}

<style>
  th{
    font-family: Arial;
    font-size: 10pt;
    border-top: solid 1px rgb(125, 125, 125) !important; 
    border-bottom: solid 1px rgb(125, 125, 125); 
  }
  td{
    font-family: Arial;
    font-size: 10pt;
    border-top: solid 1px rgb(125, 125, 125) !important; 
    border-bottom: solid 1px rgb(125, 125, 125); 
  }
  .border-right {
    border-right: solid 1px rgb(125, 125, 125); 
  }
  .border-left {
    border-left: solid 1px rgb(125, 125, 125); 
  }

  div.row {
    
  }

  .flex {
    display: flex-inline;
  }




</style>
{% endblock %}

{% block content %}

<div class="container">
  <div class="col-md-12">
    <div class="">
      <h1>Scan progress</h1>
      {% if not question %}
      <p class="lead">Select a question.</p>
      {% endif %}
      <div class="row">
        {% if questions %}
        <div class="dropdown" id="question-dropdown">
          <a class="btn {{ question|yesno:"btn-default,btn-primary" }} btn-lg dropdown-toggle" type="button" data-toggle="dropdown">
            {% if question %}
            {{ question.exam.code }}-{{ question.position }} {{ question.exam.name }} - {{ question.name }}
            {% else %}
            Select question
            {% endif %}
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            {% for q in questions %}
                <li {% if question == q %} class="active" {% endif %}><a href="{% url 'exam:admin-scan-progress' question_id=q.pk %}">{{ q.exam.code }}-{{ q.position }} {{ q.exam.name }} - {{ q.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
        <br>
        {% else %}
        <p class="alert alert-info">No question available.</p>
        {% endif %}
      </div>
      {% if question %}
        <div class="">
        <p><strong>In Progress:</strong> {{ scans_remaining }}</p>
        <p><strong>Scanned:</strong> {{ scans_done }}</p>
        <br>
        <p><strong>Last scanned:</strong></p>
        <div class="flex">
          <table class="table">
            {% for doc_column in documents %}
              <tr>
                {% for doc in doc_column %}
                  <td class="border-left">{{ doc.participant.code }} </td>
                  <!--{{ doc.barcode_num_pages }} / {{ doc.extra_num_pages }}-->
                  <!--<td><time datetime="{{ doc.timestamp|date:"c" }}" data-format="HH:mm:ss"></time></td>-->
                  <td class="border-right">
                    <div class="btn-group">
                      {% if doc.scan_status == "S" %}
                        <a class="btn btn-success btn-xs" href="{% url 'exam:scan-exam-pos-participant' exam_id=doc.participant.exam.pk participant_id=doc.participant.pk position=doc.position %}" title="Scan ({{ doc.timestamp|date:'d.M. H:m:s' }})" data-toggle="tooltip"><i class="fa fa-fw fa-file-pdf-o"></i></a>
                        {% if doc.scan_file_orig %}
                          <a class="btn btn-default btn-xs" href="{% url 'exam:scan-orig-exam-pos-participant' exam_id=doc.participant.exam.pk participant_id=doc.participant.pk position=doc.position %}" title="Full scan" data-toggle="tooltip"><i class="fa fa-fw fa-file-pdf-o"></i></a>
                        {% endif %}
                      {% endif %}
                      {% if can_mark %}
                        <a class="btn btn-default btn-xs" href="{% url 'marking:official-marking-detail' question_id=question.pk delegation_id=doc.participant.delegation.pk %}" title="Go to marking" data-toggle="tooltip">Marking</a>
                      {% endif %}
                    </div>
                  </td>
                {% endfor %}
              </tr>
            {% endfor %}
          </table>
        </div>
      {% endif %}
      </div>
    </div>
  </div>




{% endblock %}


{% block extra-script %}
<script>
$('document').ready(function(){
   $("time[data-format]").each(function () {
              var el = $(this);
              var dt = moment(el.attr("datetime"));
              el.text(dt.format(el.data("format")));
          });
    $(document).on('click', '#reload', function(event){
        location.reload();
    });

    // Activates tooltipls
    $('.btn').tooltip({containter: ".parent"});

}); // $(document).ready()
</script>
{% endblock %}

templates/ipho_exam/api_keys.html
{% extends "ipho_exam/base.html" %}
{% load static %}
{% load exam_utils_tags %}
{% load crispy_forms_tags %}

{% block extra-head %}
<style>
.div-inline{
    display:inline-block;
}
</style>
{% endblock %}

{% block breadcrumb %}
<li><a href="#">Admin</a></li>
<li class="active">API Keys</li>
{% endblock %}

{% block pageheader %}<h1>API Key</h1>{% endblock %}

{% block exam-content %}
<p class="lead">
These API Keys have read/write access to the exam documents table.
Keys can be added and modified in the application settings.
</p>

<p class="alert alert-info">The API endpoints are described at <a href="{% url 'api-exam:schema' %}" class="alert-link">API schema</a>.</p>

{% for name, key in EXAM_TOOLS_API_KEYS.items %}
<h3>{{ name }}</h3>
<div class="well well-sm">{{ key }}</div>
{% endfor %}

{% endblock %}

templates/ipho_exam/auto_translate_cost_control.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra-head %}
<meta http-equiv="refresh" content="5" />

<style>
  th{
    font-family: Arial;
    font-size: 16pt;
  }
  td{
    font-family: Arial;
    font-size: 16pt;
  }
  table.feedbacks th{
    font-family: Arial;
    font-size: 16pt;
  }
  table.feedbacks td{
    font-family: Arial;
    font-size: 16pt;
  }

  /*.large{
    font-family: Arial;
    font-size: 50pt;
  }*/

  .flex {
    display: flex-inline;
  }




</style>
{% endblock %}

{% block content %}

<div class="container">

  <div class="col-md-12">

        <div class="">
            <h1>Auto translate counts/costs</h1>
            <div class="">
                <p><strong>Total translated character count (includes chached translations):</strong> {{ total_count }}</p>
                <p><strong>Actual character count sent to translation service:</strong> {{ sent_count }}</p>
                <p><strong>Total auto translate cost:</strong> {{ sent_cost|floatformat:"-2" }}$</p>
                
                
                <br>
                <table class="table table-condensed">
                    <tr>
                      <th>Delegation</th>
                      <th>Count</th>
                      <th>Cost</th>
                    </tr>
                    {% for row in delegation_counts %}
                    <tr>
                        <td>{{ row.name }}</td>
                        <td>{{ row.auto_translate_char_count }}</td>
                        <td>{{ row.costs|floatformat:2 }}$</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

        </div>

  </div>




{% endblock %}


{% block extra-script %}
<script>
$('document').ready(function(){

    $(document).on('click', '#reload', function(event){
        location.reload();
    });

    // Activates tooltipls
    $('.btn').tooltip({containter: ".parent"});

}); // $(document).ready()
</script>
{% endblock %}

templates/ipho_exam/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="page-header">
      <h1>Exams tools</h1>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Step-by-step</h3></div>
                <div class="list-group">
                    <a class="list-group-item" href="{% url 'exam:wizard' %}">
                        Get started!
                        <span class="pull-right"><i class="fa fa-angle-double-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Translations</h3></div>
                <div class="list-group">
                    <a class="list-group-item" href="{% url 'exam:language-list' %}">
                        Define languages
                        <span class="pull-right"><i class="fa fa-angle-double-right"></i></span>
                    </a>
                </div>
                <div class="list-group">
                    <a class="list-group-item" href="{% url 'exam:list' %}">
                        My translations
                        <span class="pull-right"><i class="fa fa-angle-double-right"></i></span>
                    </a>
                </div>
                <div class="list-group">
                    <a class="list-group-item" href="{% url 'exam:submission-exam-list' %}">
                        Final submission
                        <span class="pull-right"><i class="fa fa-angle-double-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Feedbacks</h3></div>
                <div class="list-group">
                    <a class="list-group-item" href="{% url 'exam:exam-view' %}">
                        Submit exam feedbacks
                        <span class="pull-right"><i class="fa fa-angle-double-right"></i></span>
                    </a>
                    <a class="list-group-item" href="{% url 'exam:feedbacks-list' %}">
                        View exam feedbacks
                        <span class="pull-right"><i class="fa fa-angle-double-right"></i></span>
                    </a>
                </div>
            </div>
        </div>
    </div>

</div> <!-- /container -->

{% endblock %}

templates/ipho_exam/missing_figure.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <div class="container text-center">
    <h1>Missing Figure Error</h1>
    <p>
      Missing figure with id: {{ figid }}.
    </p>
    <div class="panel panel-default">
        <div class="panel-body">
          <p class="text-muted">
            The figure with id: {{ figid }} is missing. If not yet done so, please upload the figure using the <a href="{% url 'exam:figures'%}">Figure Management</a> and put the generated id in the attributes of the figure block in question you want to see the pdf of.
          </p>
        </div>
    </div>
  </div>
</div>

{% endblock %}

templates/ipho_exam/pdf_task.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container" style="">
    <p class="lead">Your PDF document is being prepared.</p>

    <p>This page will refresh automatically as soon as the job has completed.</p>

    <div class="progress" style="width: 60%; margin: 0 auto;">
      <div class="progress-bar progress-bar-striped active" role="progressbar" style="width: 100%">
          Preparing PDF...
      </div>
    </div>

    <hr style="width=80%" />

    <p class="small text-muted">Job status is <span id="task-status">{{ task.status }}</span>. Id {{ task.id }}. Last check <span id="time-lastcheck"></span>.</p>

</div>
{% endblock %}

{% block extra-script %}
<script src="{% static "moment.min.js" %}"></script>
<script>
$(function() {

    var last_check = new Date();
    var taskStatus = 'PENDING';
    var taskReady = false;
    var timer = null;
    function updateStatus() {
        $.ajax({
            url: '{% url 'exam:pdf-task-status' token=task.id %}',
            dataType: 'json',
            success: function(data) {
                taskReady = data['ready'];
                taskStatus = data['status'];
                last_check = new Date();

                var status_text = '<abbr data-toggle="tooltip" title="'+last_check.toString()+'" >'+moment(last_check).fromNow()+'</abbr>';
                $('#time-lastcheck')
                    .html(status_text)
                    .find('[data-toggle="tooltip"]').tooltip();
                $('#task-status').html(taskStatus);

                if (taskReady) {
                    clearInterval(timer);
                    location.reload();
                }
            },
        });
    }
    updateStatus();
    timer = setInterval(updateStatus, 10000);

});
</script>
{% endblock %}

templates/ipho_exam/tex_error.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <div class="container text-center">
    <h1>PDF Error</h1>
    <p>
      An error occured when generating the PDF document. Please verify that you do not have errors in the Latex formulae.
    </p>
    <div class="panel panel-default">
        <div class="panel-body">
          <p class="text-muted">
            <i class="fa fa-lightbulb-o"></i> <a href="{% url 'exam:pdf-task-log' token=task_id %}">View the error log</a>
          </p>
          <p class="text-muted">
            Error code: {{ error_code }}. Task id: {{ task_id }}.
          </p>
        </div>
    </div>
    <p>
      If the error persist, please contact the exam tools team at <a href="mailto:exam-tools-users@oly-exams.org"><i class="fa fa-envelope-o"></i> exam-tools-users@oly-exams.org</a>.
    </p>
  </div>
</div>

{% endblock %}